# Generated by Django 5.2.7 on 2025-11-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_url', models.URLField()),
                ('link_url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
